[book]
authors = ["ZhenYu Liu"]
language = "zh"
src = "src"
title = "(Not very) Advanced Marcoeconomics"
text-direction = "ltr"

[preprocessor.katex]
after = ["links"]
trust = true

[preprocessor.numeq]
prefix = true
global = false

[preprocessor.alerts]